url: https://rust.code-maven.com
repo: https://github.com/szabgab/rust.code-maven.com
branch: main
site_name: Rust programming language
link_to_source: true
footer: If you'd like to get notification when I add new content to the site [register here](/subscribe).
tags:
  title: Tags
  description: Articles about Rust with tags
archive:
  title: Archive
  description: List of all the articles about the Rust programming language
navbar:
  start:
    - path: /
      title: Home
    - path: /tags/
      title: Tags
    - path: /slides/
      title: Slides
    - path: /subscribe
      title: Subscribe
  end:
    - path: /archive
      title: Archive
    - path: /about
      title: About

