[package]
name = "two-executables"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "one_exe"
path = "src/one.rs"

[[bin]]
name = "two"
path = "src/two.rs"


